### ISSUE TITLE
add force_update option for discovery

### ISSUE THREAD

**Issue by IsaacBreuer** [tony-fav/tasmota-blerry#46]
if possible to add force_update as optional config to be added to the discovery topic.

**Comment by tony-fav** [comment]
This should already be possibly with discovery_override. Here's an example for state class, you could adapt for force updated. The YAML below needs to be converted to JSON for use in the config. 

discovery packet overrides for some sensors of a single device
```yaml
devices:
  D81E7A38ED1D/1:
    model: WoHand
    alias: dev_WoHand
  A4C138A8E41B:
    model: ATCpvvx
    alias: dev_ATCpvvx
    discovery_override:
      Temperature:
        stat_cla: measurement
      Humidity:
        stat_cla: measurement
      DewPoint:
        stat_cla: measurement
```

discovery packet overrides for some sensors of all devices
```yaml
devices:
  D81E7A38ED1D/1:
    model: WoHand
    alias: dev_WoHand
  A4C138A8E41B:
    model: ATCpvvx
    alias: dev_ATCpvvx
override:
  discovery_override:
    Temperature:
      stat_cla: measurement
    Humidity:
      stat_cla: measurement
    DewPoint:
      stat_cla: measurement
```
